--- !ruby/object:Claret::Project 
items: 
- &id001 !ruby/object:Claret::Task 
  contributes_to: []

  dependents: 
  - &id002 !ruby/object:Claret::Task 
    contributes_to: 
    - *id001
    dependents: 
    - &id005 !ruby/object:Claret::Task 
      contributes_to: 
      - *id001
      - *id002
      - &id006 !ruby/object:Claret::Milestone 
        dependents: 
        - *id005
        - &id008 !ruby/object:Claret::Task 
          contributes_to: 
          - *id001
          - *id002
          - *id006
          dependents: 
          - &id004 !ruby/object:Claret::Task 
            contributes_to: 
            - &id003 !ruby/object:Claret::Task 
              contributes_to: 
              - *id001
              - *id002
              dependents: []

              id: 2
              name: Create routing servlet
            - &id007 !ruby/object:Claret::Milestone 
              dependents: 
              - *id004
              - &id017 !ruby/object:Claret::Task 
                contributes_to: 
                - *id003
                - *id007
                - *id004
                - *id005
                - *id008
                - &id010 !ruby/object:Claret::Task 
                  contributes_to: 
                  - *id001
                  - *id002
                  - *id006
                  dependents: 
                  - *id004
                  - *id017
                  - &id018 !ruby/object:Claret::Task 
                    contributes_to: 
                    - *id003
                    - *id007
                    - *id004
                    - *id005
                    - *id008
                    - *id010
                    dependents: []

                    finish_date: &id009 2008-11-18 17:35:38.101412 -05:00
                    id: 7
                    name: setup JBoss
                    start_date: *id009
                  - &id013 !ruby/object:Claret::Task 
                    contributes_to: 
                    - *id003
                    - *id007
                    - &id014 !ruby/object:Claret::Task 
                      contributes_to: 
                      - *id003
                      - *id007
                      - *id005
                      - *id008
                      - *id010
                      dependents: 
                      - *id013
                      finish_date: &id011 2008-11-18 17:35:59.242359 -05:00
                      id: 9
                      name: deploy dummy stuff to test environment
                      start_date: *id011
                    - *id005
                    - *id008
                    - *id010
                    dependents: 
                    - *id004
                    finish_date: &id012 2008-11-18 17:35:53.951328 -05:00
                    id: 8
                    name: make dummy servlet/JSP
                    start_date: *id012
                  - *id014
                  finish_date: &id015 2008-11-18 19:14:12.189605 -05:00
                  id: 13
                  name: Create parameters parser
                  start_date: *id015
                dependents: []

                finish_date: &id016 2008-11-18 17:35:41.715117 -05:00
                id: 6
                name: determine deployment layout
                start_date: *id016
              - *id018
              - *id013
              - *id014
              estimated_achieve_date: 
              id: 10
              name: Environment set up
            - *id013
            - *id005
            - *id008
            - *id010
            dependents: 
            - *id017
            - *id018
            finish_date: &id019 2008-11-18 17:35:47.809925 -05:00
            id: 5
            name: Create build.xml
            start_date: *id019
          - *id017
          - *id018
          - *id013
          - *id014
          finish_date: &id020 2008-11-18 21:23:40.372835 -05:00
          id: 12
          name: Create controller finder
          start_date: *id020
        - *id010
        - &id025 !ruby/object:Claret::Task 
          contributes_to: 
          - *id006
          dependents: []

          finish_date: &id021 2008-11-19 14:41:19.825332 -05:00
          id: 17
          name: Create routing servlet to use the orchestration class
          start_date: *id021
        - &id026 !ruby/object:Claret::Task 
          contributes_to: 
          - *id006
          dependents: []

          finish_date: &id022 2008-11-18 22:32:52.405962 -05:00
          id: 18
          name: Create class to call set methods on the controller
          start_date: *id022
        - &id027 !ruby/object:Claret::Task 
          contributes_to: 
          - *id006
          dependents: []

          finish_date: &id023 2008-11-19 14:40:49.433318 -05:00
          id: 20
          name: Create response object to communicate results
          start_date: *id023
        estimated_achieve_date: 
        id: 14
        name: Routing Servlet created
      dependents: 
      - *id004
      - *id017
      - *id018
      - *id013
      - *id014
      finish_date: &id024 2008-11-18 20:58:19.751997 -05:00
      id: 11
      name: Create route parser
      start_date: *id024
    - *id008
    - *id010
    id: 4
    name: Create JSP helpers
  - *id005
  - *id008
  - *id010
  id: 3
  name: Create sample application
- *id002
- *id004
- *id017
- *id018
- *id013
- *id014
- *id007
- *id005
- *id008
- *id010
- *id006
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 15
  name: Improve error handling in routing parser
- *id025
- *id026
- *id027
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 21
  name: Make servlet more robust
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 22
  name: Invert dependencies in servlet
- !ruby/object:Claret::Task 
  contributes_to: []

  dependents: []

  id: 23
  name: Figure out how to make data available to JSPs
name: Fun Web Framework
next_id: 24
