--- !ruby/object:Claret::Project 
items: 
- &id001 !ruby/object:Claret::Task 
  contributes_to: 
  - &id002 !ruby/object:Claret::Task 
    contributes_to: []

    dependents: 
    - *id001
    - &id003 !ruby/object:Claret::Task 
      contributes_to: 
      - *id002
      dependents: 
      - *id001
      id: 4
      name: Create JSP helpers
    id: 3
    name: Create sample application
  - *id003
  dependents: 
  - &id004 !ruby/object:Claret::Task 
    contributes_to: 
    - *id001
    - &id005 !ruby/object:Claret::Milestone 
      dependents: 
      - *id004
      - &id008 !ruby/object:Claret::Task 
        contributes_to: 
        - *id001
        - *id005
        - *id004
        dependents: []

        id: 6
        name: determine deployment layout
      - &id009 !ruby/object:Claret::Task 
        contributes_to: 
        - *id001
        - *id005
        - *id004
        dependents: []

        id: 7
        name: setup JBoss
      - &id006 !ruby/object:Claret::Task 
        contributes_to: 
        - *id001
        - *id005
        - &id007 !ruby/object:Claret::Task 
          contributes_to: 
          - *id001
          - *id005
          dependents: 
          - *id006
          id: 9
          name: deploy dummy stuff to test environment
        dependents: 
        - *id004
        id: 8
        name: make dummy servlet/JSP
      - *id007
      estimated_achieve_date: 
      id: 10
      name: Environment set up
    - *id006
    dependents: 
    - *id008
    - *id009
    id: 5
    name: Create build.xml
  - *id008
  - *id009
  - *id006
  - *id007
  id: 2
  name: Create routing servlet
- *id002
- *id003
- *id004
- *id008
- *id009
- *id006
- *id007
- *id005
name: Fun Web Framework
next_id: 11
